services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=ToDoApp
      - APP_ENV=local
      - APP_KEY=base64:uJXm7Z/MyObO+D1Pa7ZAD0w+gzsrxyCD2fwA3ZQvlSU=
      - APP_DEBUG=true
      - APP_TIMEZONE=UTC
      - APP_URL=http://localhost:8000
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todo
      - DB_USERNAME=root
      - DB_PASSWORD=  # Empty password
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - CACHE_STORE=database
      - CACHE_DRIVER=file
      - CACHE_PREFIX=
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=log
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS="hello@example.com"
      - MAIL_FROM_NAME=${APP_NAME}
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - VITE_APP_NAME=${APP_NAME}
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=todo
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
